name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        auto-activate-base: false
        activate-environment: my-env # make sure this matches your environment.yml name
        
    - name: Run tests or scripts
      shell: bash -el {0} # <--- THIS IS CRITICAL FOR CONDA
      run: |
        conda info
        conda list
        # Your python commands here
