name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        auto-activate: false
        activate-environment: nexus-tv-env
        
    - name: Run tests or scripts
      shell: bash -el {0}
      run: |
        conda info
        conda list
        # If you have a specific script to run, add it below. 
        # For example: python main.py
